### ISSUE TITLE
Android Emulator

### ISSUE THREAD

**Issue by mandrewsan** [milouk/AMD-Ryzen-Hackintosh#1]
Hi, I've got a somewhat similar setup as you. I'm running AMD Ryzen 5 3600x on a  GIgabyte X570 motherboard. Same GPU. I'm on Open Core 0.6.6.

Wondering if you ever messed with an Android Emulator? I'm trying to launch an emulator but I've got this message: "Your CPU does not support required features (VT-x or SVM)." I've enabled SVM from the BIOS settings.

Any insight?

**Comment by milouk** [comment]
Yes, Android emulator wont play ever. What u can do is to use a third -party android emulator such as genie motion
